---
title: "R/exams questions"
output: webexercises::webexercises_default
---

```{r setup, include = FALSE}
library("exams2webexercises")
```

## Knowledge quiz (single-choice)

```{r schoice1, echo = FALSE, message = FALSE, results = "asis"}
exams2webexercises("swisscapital.Rmd")
```

## Knowledge quiz (multiple-choice)

```{r mchoice2, echo = FALSE, message = FALSE, results = "asis"}
exams2webexercises("capitals.Rmd")
```

## Arithmetic (numeric)

```{r num3, echo = FALSE, message = FALSE, results = "asis"}
exams2webexercises("deriv.Rnw")
```

## Arithmetic (single-choice)

```{r schoice4, echo = FALSE, message = FALSE, results = "asis"}
exams2webexercises("deriv2.Rnw")
```

## Multiple-choice with graphic

```{r mchoice5, echo = FALSE, message = FALSE, results = "asis"}
exams2webexercises("boxplots.Rmd", markup = "html") ##FIXME
```

## Multiple-choice with R output

```{r mchoice6, echo = FALSE, message = FALSE, results = "asis"}
exams2webexercises("ttest.Rmd")
```

## String question

```{r mchoice7, echo = FALSE, message = FALSE, results = "asis"}
exams2webexercises("function.Rmd")
```
