
\begin{question}
Using the data provided in \url{regression.csv} estimate a linear regression of
\texttt{y} on \texttt{x1} and \texttt{x2}. Answer the following questions.

\begin{answerlist}
  \item Proportion of variance explained (in percent):
  \item F-statistic:
  \item Characterize in your own words how the response \texttt{y} depends on the regressors \texttt{x1} and \texttt{x2}.
  \item Upload the R script you used to analyze the data.
\end{answerlist}
\end{question}

\begin{solution}
The presented results describe a semi-logarithmic regression.

\begin{Schunk}
\begin{Soutput}
Call:
lm(formula = log(y) ~ x1 + x2, data = d)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.68802 -0.67816 -0.01803  0.68866  2.35064 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept) -0.06802    0.13491  -0.504    0.616
x1           1.37863    0.13351  10.326 9.34e-15
x2          -0.21449    0.13995  -1.533    0.131

Residual standard error: 1.052 on 58 degrees of freedom
Multiple R-squared:  0.6511,	Adjusted R-squared:  0.6391 
F-statistic: 54.12 on 2 and 58 DF,  p-value: 5.472e-14
\end{Soutput}
\end{Schunk}

The mean of the response \texttt{y} increases with increasing \texttt{x1}.
If \texttt{x1} increases by 1 unit then a change of \texttt{y} by about 296.94 percent can be expected.
Also, the effect of \texttt{x1} is  significant at the 5 percent level.

Variable \texttt{x2} has no significant influence on the response at 5 percent level.

The R-squared is 0.6511 and thus 65.11 percent of the
variance of the response is explained by the regression.

The F-statistic is 54.12.

\begin{answerlist}
  \item Proportion of variance explained: 65.11 percent.
  \item F-statistic: 54.12.
  \item Characterization: semi-logarithmic.
  \item R code.
\end{answerlist}
\end{solution}

\exname{Regression cloze essay}
\extype{cloze}
\exsolution{65.11|54.12|nil|nil}
\exclozetype{num|num|essay|file}
\extol{0.1}
